# Private credentials (loaded as environment variables)

CIRCUITPY_WIFI_SSID = "WIFI_SSID"
CIRCUITPY_WIFI_PASSWORD = "WIFI_PASSWORD"
ADAFRUIT_AIO_USERNAME = "ADAFRUIT_IO_USERNAME"
ADAFRUIT_AIO_KEY = "ADAFRUIT_IO_CIRCUITPYTHON_KEY"
